### ISSUE TITLE
MailGun issue

### ISSUE THREAD

**Issue by pedrojovelli** [pedrojovelli/RioEdits#11]
O Jesse recebe de vez em quando mensagens vazias do form..

Gostariamos de saber se é algum tipo de robô... e se tem como fazer com que isso nao aconteça mais... temos a preocupacao de que clientes nosso também possam ter a mesma experiência...

![screen shot 2019-02-20 at 13 49 58](https://user-images.githubusercontent.com/15367213/53108823-73cedc00-3516-11e9-8eba-2284f8609466.png)

**Comment by fabiomrosa** [comment]
Is this solved, right?
